# Generated by Django 4.2.3 on 2025-11-06 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userbankaccount_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100)),
                ('code_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
