# Generated by Django 4.2.3 on 2025-11-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_userbankaccount_transfer_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(max_length=20)),
                ('imf_code', models.CharField(max_length=20)),
                ('insurance_code', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
