# Generated by Django 4.2.3 on 2025-11-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_usercodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_progressed',
            field=models.BooleanField(default=False),
        ),
    ]
