# Generated by Django 4.2.3 on 2025-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
