# Generated by Django 4.2.3 on 2025-11-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_pin',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
