# Generated by Django 4.2.3 on 2025-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_transfer_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_pin',
            field=models.IntegerField(null=True),
        ),
    ]
